### ISSUE TITLE
Command line -m & -p ignored

### ISSUE THREAD

**Issue by f4hla** [Raistlfiren/garmin-csv-plan#11]
Hi, 
-m and -p (also --email and --password) seem to be ignored (can be checked by adding 
        echo ('trying to log using - '. $garminUsername.' / '.$garminPassword);
in Client.php line 11 (john/doe are logged out)

I could not find quickly where the command line parameters are taken into account.
Thanks

**Comment by Raistlfiren** [comment]
Thanks for this report. I have updated the code to use the .env first and then the -m/-p flags. If it doesn't work, then please re-open this.

**Comment by f4hla** [comment]
working good!
tnx
