### ISSUE TITLE
Parser.php does not recognize repeating runs

### ISSUE THREAD

**Issue by f4hla** [Raistlfiren/garmin-csv-plan#12]
Hello
as can be seen  in ultra-80k....csv test file, we could define a run and then reuse by just entering the name of it. However, in this case it fails with 

In Parser.php line 98:                                               
  Call to a member function getName() on null  
                                               

Found that this is because we always try to build a new workout (line 189) based on type that is not repeated in case of same exercise....we need to create a "memory"
thanks :)

**Comment by pygoubet** [comment]
Hi
The PR #14 provides the ability to import the complete plan 'ultra-80k-runnersworld.csv'

**Comment by f4hla** [comment]
Tested ok 👍 👌 
Good Job!

**Comment by Raistlfiren** [comment]
I have updated the code to now include support for nested repeaters.
