### ISSUE TITLE
WEEK is ok, Week is not...

### ISSUE THREAD

**Issue by f4hla** [Raistlfiren/garmin-csv-plan#15]
Need to accept independently of CAP status (in the csv file)
:)

**Comment by Raistlfiren** [comment]
Can you show me the first few lines of your dataset please?

**Comment by f4hla** [comment]
Hello @Raistlfiren 
here is the first few lines (thanks for having waited)
--
"Week","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"
1,,,,,,,
--


Please note that I realised this issue with WEEK happened using the PR#14 from @pygoubet - this is where this issue is located since the parsing directly uses Table['WEEK'].
Regards

**Comment by Raistlfiren** [comment]
@f4hla - Please test this now. It should be fixed with the latest commits. 

Thanks
