### ISSUE TITLE
ERROR: Service 'garmin-dev' failed to build

### ISSUE THREAD

**Issue by pygoubet** [Raistlfiren/garmin-csv-plan#18]
Hi @Raistlfiren,

Following issue #17 I have tried to run the code using a container.
It does not work neither.
```
$ docker-compose up garmin-dev
Building garmin-dev
Step 1/4 : FROM php:7.4-cli-alpine
 ---> 91cefd5154f6
Step 2/4 : RUN apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS   && pecl install xdebug   && docker-php-ext-enable xdebug   && apk del .phpize-deps
 ---> Running in eaae4e5fa364
ERROR: Service 'garmin-dev' failed to build: The command '/bin/sh -c apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS   && pecl install xdebug   && docker-php-ext-enable xdebug   && apk del .phpize-deps' returned a non-zero code: 139
```
Any idea?

**Comment by Raistlfiren** [comment]
@pygoubet  - Does running the non-dev version of the project work? I am running it on Fedora and it works okay on a fresh install. Can you try removing any older containers before running?

**Comment by Raistlfiren** [comment]
Hey, I am unsure of this. I installed Docker and docker-compose, but I was unable to emulate this issue. It ran okay in my VM instance, but I am running the i386 architecture in VirtualBox. I am unable to troubleshoot this properly.

**Comment by pygoubet** [comment]
non-dev version produces the error with Raspberry Pi OS (armv7l architecture - 32 bits).
It works on an arm64 EC2 instance.
I will try to investigate ...

**Comment by Raistlfiren** [comment]
Thanks @pygoubet. If you find an answer, then that would be great. Although, it might be difficult if it is related to the architecture. I wonder if it doesn't have to do with the alpine version of PHP 7.4 docker. https://github.com/Raistlfiren/garmin-csv-plan/blob/f7746280179f1add9be788feebf7e0b3b6e4819f/docker/dev/Dockerfile#L1 Maybe try using the full blown ubuntu version by using `php:7.4-cli`

**Comment by Raistlfiren** [comment]
Hey @pygoubet - I am closing this issue. If you feel like it is still a problem, then please re-open.
