### ISSUE TITLE
ConsumerKey is invalid

### ISSUE THREAD

**Issue by claudiahdz** [Raistlfiren/garmin-csv-plan#30]
Hi!

I've been using this repo in the past to upload workouts to my Garmin. Today when trying to upload, I got a
 `ConsumerKey is invalid` error. Basically a `HTTP/2 401`. Could there be some issue with expired API Keys? Thanks!

```
The request has not been applied to the target resource because it lacks valid authentication credentials for that resource.
```

**Comment by Raistlfiren** [comment]
@claudiahdz - Was this due to 2FA? Or due to something completely unrelated? I tested this again today to verify everything is working and it does seem to be. However, my implementation of authentication might be flawed due to 2FA not being implemented in the authentication process.
