### ISSUE TITLE
Failed to create errors

### ISSUE THREAD

**Issue by mvanrompuy** [Raistlfiren/garmin-csv-plan#31]
Hi,

I'm seeing failed to create errors using the latest version of the tool:

```
Creating workouts
-----------------

 * Workout - TR 14.5k, 6.4k @ 15k to HM pace failed to create
 * Workout - LR 17.7k failed to create
 * Workout - REC 8k failed to create
 * Workout - GA 14.5k failed to create
 * Workout - LR 24.1k failed to create

                                                                                                                        
 [OK] Workout import was successful.   
```

My credentials are setup correctly in a .env file (email and password used to login on connect.garmin.com) and no 2FA is enabled on my account.

Is this a change in the login steps which has broken the tool?

**Comment by Raistlfiren** [comment]
@mvanrompuy - Please try updating to the latest release and see if things work for you. I believe Garmin decided to change the API recently as noted in this issue - https://github.com/matin/garth/issues/73

Updating the user agent seemed to fix the problem - https://github.com/Raistlfiren/garmin-csv-plan/commit/aea2cd702f540a1802f7563926e6a65ab38c12d9

Thank you for taking the time to report the issue. Hopefully, this resolves the issue for you.

**Comment by mvanrompuy** [comment]
Thanks a lot! Working as expected now.
